language: java
env:
  global:
  - secure: NJBh1QlW8mIun+RnxpecMdkOf+oWpIoS9VjTHCf/jl03nZIX7yAGOPDJmOl3wwgiDCwmp9AexY1LcGLR8Df4wBaFpq8MlYX7eVjkcrKLvkLDAe3Jj3n+XBUiTS7LeM7buHTcyqHA/c3MWz13RFZ29z7ZFfyPtW12pMKSZVPnEOcG6NYnUEyJWhAPupXYLKKz4q75Vg1J34zYW1EPNl4vLnCmtwUIHO2N/0Y7lSoJReESc3YgfKL0iNXodtPoVV204ZtmtxJsDdmp2Ylm7HgpZu/JNR/VcIp/lhCBGJXVY1QenN7OFA4iu/ZgyYPWgL92mzw24+AX74g+l0mk3UtVj3F35BMAOftzkOf/u8GJ4bgR5JUEzqch+fjao+JuMf9V1uFWJ7dQwXmLeIHtCPV8TgMvmrLGaxtzUE3TCInAWEvnmwM9eWVOG7BNOXQkJ9ziTlkBBTuhofnxU4kqs0Lk55a1BqXZVJiI+AOu83KckBOCxF9LDWh4+/qHqRVOEKq0P4ashmssIU3QmznAwq9JFZ1+KFAeJMTN/PF/aNR6CPqK1cXCur3bYJ+PxwB6HiS8awe+67GK/vk4wvy40bcaXf/ErTaAbDvmqEfIM4LOetjPhM6CJCRq+m9o5Yp/Cwp6yQBFC0igJgfQXeHWDjAr1EhQ9tT/0ojzB/gobHJldIY=
  - secure: rSfDmT1K71YQ5GymkiMeSdNolj0HS4cHJCilusPFcEGt3UxFb6pZJLzusXOWVfAdOdMNX6xY0BARRvF9duM0ZDvpyA6DSosMYnt/RqcErkY3mIiO/cHTjlyqk8Up0TqT/xjo4aT4XSLyNwhm/QqgirZJTaEDwbJ8uk4EnSVtkYBa/vkPmTs9hEAtpWHkaF38LsfyrGUzeqWONIkM4FHEE8pCsrT7NfWCZHq7ARlUB9rcT1yyCpmaBOxkbSe9tCucPNKFawiiC+MOtwpRgfOR8yr97S3cLe5J1OmO/27MBjQj0BBOP0pJQPXWfMh2+XDzpuFbDfs9uCQfZcbus4Zdn656XuZCl7PP3IH+YvLXIDJlPoxUNMdA+OqplmvJ0pJ/ay+zhw2iB4GrrrbADht5KFs+oEivGu2zHPpgJ63Ta1leFpB7b0aPtUBaDfrWh/QaKrJHcWvRduvOFapFceC152wflInIsEfGK8PTa8TIyAoc6ugiglrlkZoukkRxc65PowewxuhidBL3D5k7xWe/kkqLlJfMkmI+LSp1P2V5CHuHql454gfk8i72RkJ8Z5dBqxqD7luvE9wvJrxfcNoXunXoaLFLXaVJrP9MyNcDBpI51NaIIS4Nl4hYkZIc2c5vrMlAQAtyElZr6YIfcYfppzARMfMCCcEJ4rujc4wXJIY=

cache:
  directories:
  - "$HOME/.m2"
install: mvn -B clean compile test-compile
script: mvn -B package checkstyle:check -DskipTests
after_success:
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn -s
  .travis/settings.xml deploy -DskipTests
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" == "" && mvn -s
  .travis/settings.xml deploy -DskipTests
